"""
reindex.py — regenerates knowledge/discovery_index.yml by scanning all entity and datatable YAML files.

Run from the project root:
    python framework/tools/reindex.py
"""

from pathlib import Path
from datetime import date
import yaml

ROOT = Path(__file__).parent.parent.parent
KNOWLEDGE = ROOT / "knowledge"
INDEX_PATH = KNOWLEDGE / "discovery_index.yml"


def count_properties(yml: dict) -> tuple[int, int]:
    """Returns (confirmed_count, todo_count) for an entity file."""
    props = yml.get("properties", {})
    funcs = yml.get("functions", {})
    confirmed = len(props) + len(funcs)
    todo = len(yml.get("todo", []))
    return confirmed, todo


def count_columns(yml: dict) -> tuple[int, int]:
    """Returns (confirmed_count, todo_count) for a datatable file."""
    cols = yml.get("columns", {})
    confirmed = sum(1 for c in cols.values() if not c.get("notes", "").startswith("unconfirmed"))
    todo = len(yml.get("todo", []))
    return confirmed, todo


def count_api_commands(yml: dict) -> int:
    cmds = yml.get("api_commands", [])
    return len(cmds)


def build_index() -> dict:
    index = {
        "last_updated": str(date.today()),
        "game_version": "0.7.1",
        "summary": {
            "entities": {"total": 0, "confirmed": 0, "partial": 0, "unverified": 0, "broken": 0, "deprecated": 0},
            "datatables": {"total": 0, "confirmed": 0, "partial": 0, "unverified": 0, "broken": 0},
        },
        "entities": {},
        "datatables": {},
        "total_api_commands_ready": 0,
        "total_todo_items": 0,
    }

    # Scan entities
    entity_files = list((KNOWLEDGE / "entities").rglob("*.yml"))
    entity_files = [f for f in entity_files if not f.name.startswith("_")]

    for path in sorted(entity_files):
        try:
            yml = yaml.safe_load(path.read_text(encoding="utf-8"))
        except Exception as e:
            print(f"  Warning: Could not parse {path}: {e}")
            continue

        name = yml.get("name", path.stem)
        status = yml.get("discovery_status", "unverified")
        confirmed, todo = count_properties(yml)
        api = count_api_commands(yml)

        index["entities"][name] = {
            "status": status,
            "file": str(path.relative_to(KNOWLEDGE)),
            "properties_confirmed": confirmed,
            "properties_todo": todo,
            "api_commands_ready": api,
        }

        s = index["summary"]["entities"]
        s["total"] += 1
        s[status] = s.get(status, 0) + 1
        index["total_api_commands_ready"] += api
        index["total_todo_items"] += todo

    # Scan datatables
    dt_files = list((KNOWLEDGE / "datatables").rglob("*.yml"))
    dt_files = [f for f in dt_files if not f.name.startswith("_")]

    for path in sorted(dt_files):
        try:
            yml = yaml.safe_load(path.read_text(encoding="utf-8"))
        except Exception as e:
            print(f"  Warning: Could not parse {path}: {e}")
            continue

        name = yml.get("name", path.stem)
        status = yml.get("discovery_status", "unverified")
        confirmed, todo = count_columns(yml)
        api = count_api_commands(yml)

        index["datatables"][name] = {
            "status": status,
            "file": str(path.relative_to(KNOWLEDGE)),
            "columns_confirmed": confirmed,
            "todo_count": todo,
            "api_commands_ready": api,
        }

        s = index["summary"]["datatables"]
        s["total"] += 1
        s[status] = s.get(status, 0) + 1
        index["total_api_commands_ready"] += api
        index["total_todo_items"] += todo

    return index


def main():
    print("Reindexing knowledge base...")
    index = build_index()

    INDEX_PATH.write_text(
        "# Discovery Index -- auto-generated by framework/tools/reindex.py\n"
        "# DO NOT edit manually -- changes will be overwritten on next reindex\n\n"
        + yaml.dump(index, default_flow_style=False, allow_unicode=True),
        encoding="utf-8",
    )

    s = index["summary"]
    print(f"\nEntities: {s['entities']['total']} total "
          f"({s['entities'].get('confirmed',0)} confirmed, "
          f"{s['entities'].get('partial',0)} partial, "
          f"{s['entities'].get('unverified',0)} unverified)")
    print(f"DataTables: {s['datatables']['total']} total "
          f"({s['datatables'].get('confirmed',0)} confirmed, "
          f"{s['datatables'].get('partial',0)} partial, "
          f"{s['datatables'].get('unverified',0)} unverified)")
    print(f"API commands ready: {index['total_api_commands_ready']}")
    print(f"Open TODO items: {index['total_todo_items']}")
    print(f"\nWrote: {INDEX_PATH}")


if __name__ == "__main__":
    main()
